version: "3"
services:
  directus:
    image: directus/directus:11.3.2
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      SECRET: "replace-with-secure-random-value"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"
      CORS_ENABLED: "true" # Habilitar CORS
      CORS_ORIGIN: "http://localhost:3000" # Permitir requisições de localhost:3000
      CORS_METHODS: "GET,POST,PATCH,DELETE,OPTIONS" # Métodos permitidos
      CORS_HEADERS: "Content-Type,Authorization,Accept" # Cabeçalhos permitidos
      CORS_CREDENTIALS: "true" # Se necessário, habilitar credenciais
